version: '3.8'

services:
  app:
    image: jesmora/hnet-server:v2.0.0
    ports:
      - "56559:56559"
    environment:
      HOST: 0.0.0.0
      SECRET: "hnet-jesmora"
      HNET_USER: "Jesmora"
      HNET_PWD: "hnet-jesmora"
      REDIRECT_HOST: "www.google.com"
      MONGDB_CONNECTION: "your_mongodb_connection_string"
      MODO: "normal"
      SOCKS5: "username:password@127.0.0.1:1080"
