version: '3.8'

services:
  app:
    image: jesmora/hnet-server
    ports:
      - "56559:56559"
    environment:
      HOST: 0.0.0.0
      SECRET: "hnet-jesmora"
      REDIRECT_HOST: "www.google.com"
      MONGDB_CONNECTION: "your_mongodb_connection_string" # 请替换成你的MongoDB连接字符串
      MODO: "normal"
